### ISSUE TITLE
Build instruction in README.md is outdated

### ISSUE THREAD

**Issue by JaehyunShim** [christianrauch/raspicam2_node#7] opened 2020-07-31 03:00 UTC
@christianrauch  Hi,

I am trying to use my raspicam on a raspi3b+ board using ROS2 Dashing on Ubuntu 18.04.3 (specifcally I installed the ubuntu-18.04.3-preinstalled-server-arm64+raspi3.img.xz image file from this [link](http://old-releases.ubuntu.com/releases/18.04.3/)) 
I followed the instruction written on the README.md file, and when I colcon-builded the package from this repository, I got the error code below.
```sh
/opt/vc/lib/libbcm_host.so: error adding symbols: File in wrong format
```

I googled the error code and it seems like the problem for this issue lies in the CMakeLists.txt file. 
Can I get help or advice? 
Thank you for your help in advance, 
Ryan

**Comment by kgallowa** [comment] 2020-08-07 17:57
Just a note that I'm trying to do the exact same thing (i.e. install raspicam on a raspi3b+ board using ROS2 Dashing on Ubuntu 18.04.3) and I'm getting the same build error.

**Comment by christianrauch** [comment] 2020-08-08 11:14
Do the build instructions work for you on **Raspbian**?

I've not tried to build the node on Ubuntu. I will give it a try on a Raspberry Pi 2 with Ubuntu to see if I get the same errors and how to resolve them.

The message `error adding symbols: File in the wrong format` indicates that you are trying to link library `libbcm_host.so` with a different instruction set (CPU architecture). You have to make sure that you compile the node with the same CPU architecture that `libbcm_host.so` has.

Edit:
It seems that there are not binary ROS2 packages for Ubuntu `armhf` available, so I will skip the Ubuntu test since I do not have a 64 bit Raspberry Pi (versions 3 or 4) with an `arm64` architecture.

@rjshim @kgallowa Can you check the following:
1. Does `file /opt/vc/lib/libbcm_host.so` report the same architecture as `dpkg --print-architecture` on your system?
2. Do the build instructions work on a [32bit `armhf` Ubuntu](https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04.1&architecture=armhf+raspi)?
3. Do the build instructions work on Raspbian (32bit/64bit)?

**Comment by kgallowa** [comment] 2020-08-08 11:49
@christianrauch, thanks for your reply. I haven't tried on Raspian; is there a ROS2 distro that will build on Raspian? 

I'll try your suggestions and reply. As background, the reason I'm using 64-bit Ubuntu Server 18 is that I'm setting up a Turtlebot3 for ROS2 Dashing (https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_setup/). I'm guessing that's what @rjshim is working on as well.

**Comment by christianrauch** [comment] 2020-08-08 11:52
> is there a ROS2 distro that will build on Raspian?

You should be able to [build ROS2 from source](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/) on any recent version of Raspbian or Ubuntu. However, building from source will take some time, especially on older Raspberry Pis.

**Comment by kgallowa** [comment] 2020-08-10 17:06
One update here: I treid your first recommendation and found that the file /opt/vc/lib/libbcm_host.so is 32-bit and dpkg --print-architecture reports arm64. So it appears that your diagnosis was correct regarding mismatch between system architecture and object file. 

I haven't had a chance to try your other recommendations yet.

**Comment by christianrauch** [comment] 2020-08-10 21:53
I would try to get the 64bit version of the BCM libraries. You may have to compile https://github.com/raspberrypi/userland manually.

Alternatively, you have to instruct CMake to build in 32bit and not in the native CPU architecture. You can do this from the command-line. Something like `colcon build --cmake-args="-DCMAKE_CXX_FLAGS=-m32"` should do the trick.

If there is a way to do this automatically within CMake, e.g. compile in 32bit if any of the linked libraries is 32bit, I am happy to review a pull request that implements this automatic behaviour.

**Comment by kgallowa** [comment] 2020-08-11 21:01
Thanks for the suggestions. Here's a couple updates:
1)  I tried obtaining the 64-bit versions of the necessary libraries, but compiling  https://github.com/raspberrypi/userland manually (with --aarch64 option) works but doesn't build all of the libraries. In particular, it appears that it doesn't build MMAL libraries and others we need for the camera. (The way I got the 32-bit versions of those libraries was through rpi-update https://github.com/Hexxeh/rpi-update, and i don't see a way to get 64-bit versions through that method.)

2) I tried instructing CMake to build in 32bit using colcon build --cmake-args="-DCMAKE_CXX_FLAGS=-m32", but the build fails with errors that say "c++: error: unrecognized command line option '-m32'".  Any ideas on what's going on there?

Thanks for your help!

**Comment by christianrauch** [comment] 2020-08-15 00:24
> Any ideas on what's going on there?

Nope. And I don't have any of the 64bit capable Raspberry Pis to actually test this. There might be a couple of other steps required to make CMake compile for the 32bit architecture.

From my perspective, the issue is related to the mismatching binary format of the BMC library and I don't really know how this can be solved in this repo. You either have to provide the dependencies in the native binary format of the host architecture, you you find a way to force CMake to compile in a different architecture.

As an alternative to he `raspicam2_node` node, you can try to get the V4L2 driver for the Raspberry Pi camera running (https://www.raspberrypi.org/forums/viewtopic.php?t=62364, https://www.ics.com/blog/raspberry-pi-camera-module) and use the [`v4l2_camera` node for ROS2](https://gitlab.com/boldhearts/ros2_v4l2_camera).

**Comment by kgallowa** [comment] 2020-08-17 10:33
Thanks for the update. I agree that at this point it doesn't seem to be something that can/should be solved in your repo. I'll continue to try some different options as I have time, but as far as I'm concerned you're welcome to close this issue. (Of course, I wasn't the OP, so I'll defer!)

**Comment by christianrauch** [comment] 2020-08-24 22:22
I will close this for now since I don't see how this can be fixed with the build settings in the node. If you can provide a solution in the CMake file to build it correctly with the same architecture as the library, I will be happy to review it.

**Closed as completed** 2020-08-24 22:22 UTC

**Comment by JaehyunShim** [comment] 2020-08-27 05:08
@christianrauch 
Thank you very much for the comments above.
As Ubuntu 18.04 and 20.04 Mate have been released, I installed those OSs and tested this repository on my raspi again. 
It worked perfectly fine and I will guide those presumably Turtlebot3 users to use Ubuntu Mate instead of Ubuntu Server.
Thank you.

@kgallowa 
My coworkers will test if all of the TB3 functions work fine and update the manual ([link](https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_setup/)) soon. 
If you have any further questions, please leaven them at this [link](https://github.com/ROBOTIS-GIT/turtlebot3/issues).

Ryan

**Comment by christianrauch** [comment] 2020-08-27 08:50
@rjshim Thanks for following up on this.

> As Ubuntu 18.04 and 20.04 Mate have been released, I installed those OSs and tested this repository on my raspi again.
It worked perfectly fine

What solves the issue in the end? I don't think that the Ubuntu flavour per se has an influence on the compilation. Might it be that your Ubuntu Mate image is just a 32bit (`armhf`) OS version? Maybe it is enough to recommend users to install a `armhf` version of Ubuntu to compile the `raspicam2_node` without further modifications.

**Comment by kgallowa** [comment] 2020-08-27 12:20
@rjshim That's great! Thanks for the update. I'll look for the update in the manual.

**Comment by JaehyunShim** [comment] 2020-08-28 02:09
I am not working on low-level architectures so below is my personal guess based on some references that I found.

1. Raspberry PI 3~4 models are all with 64-bit MCUs (ref: [link](https://ubuntu-mate.org/download/)). There is no issue with using a 64-bit OS on those models. 
2. libbcm_host.so related problems on 64-bit OS versions have been fixed recently. (ref: [link](https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/12)). I used a 64-bit OS, not 32-bit, and I think I downloaded an updated version (let me know if I am wrong about this point).
3. We never tested our systems on a 32-bit OS, so we will just change the manual and guide users to use the latest & working 64-bit version. While working on building up ROS2 systems, we found lots of issues that we could not understand, e.g., ROS2 message communication works in version 18.04.1 and 18.04.3 but doesn't work in 18.04.2 and 18.04.4. However, fixing those bugs is out of our development coverage, but more for OSRF. Instead, we will test, at least, all the features we implemented on the robot, and make sure that they work without any issues.

@christianrauch Thank you for your help and advice.
@kgallowa Thank you for your interest in our products.
Ryan
